version: '3.8'

services:
  vogcodechallenge.api:
    image: ${DOCKER_REGISTRY-}vogcodechallengeapi
    container_name: "VogCodeChallenge.API"
    build:
      context: .
      dockerfile: VogCodeChallenge.API/Dockerfile
    ports:
      - "30000:80"
      - "30001:443"